name: Deploy to Hostinger

# Using updated SSH key for deployment
on:
  push:
    branches:
      - main # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la .github/workflows/

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Update Composer dependencies
        run: |
          composer update --no-interaction --prefer-dist --with-all-dependencies

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Debug SSH connection
        run: |
          echo "Testing SSH connection..."
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "SSH key file created. Checking content:"
          ls -la ~/.ssh/deploy_key
          echo "First few lines of the key file:"
          head -3 ~/.ssh/deploy_key
          echo "SSH key format check:"
          ssh-keygen -l -f ~/.ssh/deploy_key || echo "Key format check failed"
          echo "Public key content:"
          ssh-keygen -y -f ~/.ssh/deploy_key || echo "Could not extract public key"
          echo "SSH connection test with verbose output:"
          ssh -v -p 65002 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no u179209572@145.223.76.158 "echo 'SSH connection successful'" || echo "SSH connection failed"

      - name: Check server directories and permissions
        run: |
          echo "Checking available directories and permissions..."
          ssh -p 65002 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no u179209572@145.223.76.158 "pwd && ls -la && echo '--- Home directory ---' && ls -la ~ && echo '--- Public HTML directory ---' && ls -la public_html 2>/dev/null || echo 'public_html not found in current directory' && echo '--- Checking if we can access public_html ---' && ls -la ~/public_html 2>/dev/null || echo 'public_html not found in home'"
          echo "Directory check completed"

      - name: Create deployment directory
        run: |
          echo "Creating deployment directory..."
          ssh -p 65002 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no u179209572@145.223.76.158 "mkdir -p domains/everythingproperty.ng/public_html/api/admin"
          echo "Directory created successfully"

      - name: Backup existing configuration files
        run: |
          echo "Backing up existing configuration files..."
          ssh -p 65002 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no u179209572@145.223.76.158 "cd domains/everythingproperty.ng/public_html/api/admin && [ -f .env ] && cp .env .env.backup || echo 'No .env to backup' && [ -f .htaccess ] && cp .htaccess .htaccess.backup || echo 'No .htaccess to backup' && [ -f public/.htaccess ] && cp public/.htaccess public/.htaccess.backup || echo 'No public/.htaccess to backup'"
          echo "Backup completed"

      - name: Deploy to Hostinger
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --exclude '.git' --exclude '.github' --exclude 'node_modules' --exclude '.DS_Store' --exclude 'tests' --exclude 'storage' --exclude '.env' --exclude '.htaccess' --exclude 'public/.htaccess'
          path: ./
          remote_path: domains/everythingproperty.ng/public_html/api/admin/
          remote_host: 145.223.76.158
          remote_user: u179209572
          remote_key: ${{ secrets.HOSTINGER_SSH_KEY }}
          remote_port: 65002

      - name: Restore configuration files
        run: |
          echo "Restoring configuration files..."
          ssh -p 65002 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no u179209572@145.223.76.158 "cd domains/everythingproperty.ng/public_html/api/admin && [ -f .env.backup ] && mv .env.backup .env || echo 'No .env backup to restore' && [ -f .htaccess.backup ] && mv .htaccess.backup .htaccess || echo 'No .htaccess backup to restore' && [ -f public/.htaccess.backup ] && mv public/.htaccess.backup public/.htaccess || echo 'No public/.htaccess backup to restore'"
          echo "Configuration files restored"

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          ssh -p 65002 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no u179209572@145.223.76.158 "echo '--- Contents of domains/everythingproperty.ng/public_html/api/admin ---' && ls -la domains/everythingproperty.ng/public_html/api/admin && echo '--- Checking for app directory (Laravel) ---' && ls -la domains/everythingproperty.ng/public_html/api/admin/app 2>/dev/null || echo 'app directory not found' && echo '--- Checking for public directory ---' && ls -la domains/everythingproperty.ng/public_html/api/admin/public 2>/dev/null || echo 'public directory not found'"
          echo "Deployment verification completed"

      - name: Setup Laravel environment
        run: |
          echo "Setting up Laravel environment..."
          ssh -p 65002 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no u179209572@145.223.76.158 "cd domains/everythingproperty.ng/public_html/api/admin && [ ! -f .env ] && cp .env.example .env || echo '.env already exists, skipping' && chmod -R 755 bootstrap/cache && echo 'Laravel environment setup completed'"
          echo "Environment setup completed"

      - name: Generate Laravel key
        run: |
          echo "Generating Laravel application key..."
          ssh -p 65002 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no u179209572@145.223.76.158 "cd domains/everythingproperty.ng/public_html/api/admin && php artisan key:generate --force"
          echo "Application key generated"
